(()=>{(()=>{function p(e){var t=document.createElement("div");return t.innerHTML=e.trim(),t.firstChild}function i(e,t,o){var s=new RegExp("([?&])"+t+"=.*?(&|$)","i"),r=e.indexOf("?")!==-1?"&":"?";return e.match(s)?e=e.replace(s,"$1"+t+"="+o+"$2"):e=e+r+t+"="+o,e}function l(){let e=document.querySelectorAll('[data-tid="threadBodyMedia"]');e&&e.forEach(t=>{let o=t.querySelector(".top-row-text-container");if(t&&o){if(!o.hasAttribute("data-hasquote")){let s=document.createElement("button");s.classList.add("teams-custom-quote-message-button"),Object.assign(s.style,h),o.appendChild(s),o.setAttribute("data-hasquote","true"),s.addEventListener("click",y)}if(!o.hasAttribute("data-hasgoto")){let s=t.querySelector("blockquote[itemtype='http://schema.skype.com/Reply']");s&&s.hasAttribute("itemid")&&(s.addEventListener("click",r=>{let c=r.currentTarget.getAttribute("itemid"),a=i(window.location.href,"messageId",""),n=i(window.location.href,"messageId",c);window.location.href=a,window.location.href=n}),o.setAttribute("data-hasgoto","true"))}}})}function f(e){let o=/(\{){0,1}[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}(\}){0,1}/.exec(e);return o!=null?e.substr(0,o.index)+o[0]:null}function y(e){u();let t=e.target.offsetParent.querySelector('[data-tid="messageBodyContent"]').cloneNode(!0),o=t.querySelector("blockquote[itemtype='http://schema.skype.com/Reply']");o&&o.remove();let s=t.innerText,r=e.target.offsetParent.querySelector('[data-tid="threadBodyDisplayName"]').innerText,c=e.target.offsetParent.offsetParent.offsetParent.querySelector('[data-tid="threadBodyMedia"]').id.substr(1),a=i(window.location.href,"messageId",c),n=f(e.target.offsetParent.offsetParent.offsetParent.offsetParent.offsetParent.dataset.scrollId),d=p(`
        <blockquote itemscope itemtype="http://schema.skype.com/Reply" itemid="${c}">
          <strong itemprop="mri" itemid="${n}">${r}</strong>
          <span itemprop="time" itemid="${c}"></span>
          <p itemprop="preview">
            ${s}
          </p>
        </blockquote>
      `);d.addEventListener("click",()=>{u()});let m=document.querySelector(".cke_wysiwyg_div"),b=document.querySelector(".ts-text-watermark");b.style.display="none",m.insertBefore(d,m.firstChild);let q=document.querySelector(".cke_contents");q.style.height=d.offsetHeight+40+"px"}function u(){let e=document.querySelector(".cke_wysiwyg_div").querySelector("blockquote");if(e&&e.remove(),!document.querySelector(".cke_wysiwyg_div").innerText.trim()){let t=document.querySelector(".cke_wysiwyg_div"),o=document.querySelector(".cke_contents"),s=document.querySelector(".ts-text-watermark");t.innerHTML="<div> <br> </div>",s.style.display="block",o.style.height="33px"}}function g(){let e=document.getElementsByTagName("head")[0],t=document.createElement("style"),o=document.createTextNode(`
      .teams-custom-quote-message-button { height: 16px; width: 16px; background-image: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAFo9M/3AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAGlSURBVChTnZOxSwJRHMfvpogwaAgaogNFCM+93LolG9qabhCCECeHJhe3hrZaHHNwTHD1D7ghx5YjBIMLRUIHl/OSjvO9vr93Ty/xiugDX97v+/v93k/fe5yyhHOeoiV0QIV4NpsNXSaTQQc/CB2A2ZVhDKheQE/SKkqhUGCqqjKENOdQJBE80jqdTgORIJDMQ01pI5C8TKVSYsRC9XodaX5EdQHMfqlUomQT2oZuarUa63Q60dHiQOOGDP8AY8yT4TqDweAzn6dD8FOZinAch866PIGu6ywIgleqCXzff8MiiosbI00mExdryHw+78qfUKFjbHpPJBLkDdmCLZw/y1AAfwV1pY0HDXcyXAWFE5og7d/BpvPxeDyrVCoM8frD/gSazX6/76fTaXEDyWSSNxoN1mq1eK/Xo2Ev0DW0Ge74BpJOuVxe3vNvMgyDjUajD+w5g49AQqPHKRaL4h1yuRz3PI+5rsuGwyG3LItVq1WuaZoYZJom/SsLos8nAok9vJndbrdj7wC5Lejetm0aSD0PsrQKCjuQLm0sqN9CM2n/i6J8AYR+NYM1RnyMAAAAAElFTkSuQmCC') !important; background-size: 16px 16px !important; }
      .teams-custom-quote-message-button:hover { color: #a2c0f5 !important; }
      .ts-message-thread-body .message-body-top-row .top-row-text-container { justify-content: space-between; }
      blockquote[itemtype='http://schema.skype.com/Reply'] { cursor: pointer; }
      .cke_wysiwyg_div blockquote[itemtype='http://schema.skype.com/Reply'] { cursor: default; pointer-events: none; }
      .cke_wysiwyg_div blockquote[itemtype='http://schema.skype.com/Reply']:before { content: 'x'; font-weight: bold; pointer-events: all; cursor: pointer; position: absolute; right: 20px; top: 10px; }
    `);t.type="text/css",t.styleSheet?t.styleSheet.cssText=o.nodeValue:t.appendChild(o),e.appendChild(t)}let h={margin:"0 0 0 2em",padding:"0","border-radius":"2px",outline:"none",border:"none",cursor:"pointer",background:"transparent"};function A(e){let t={attributes:!1,childList:!0,subtree:!0,characterData:!1,characterDataOldValue:!1,attributeOldValue:!1},o=function(r,c){if(r){for(let a=0;a<r.length;a++)if(r[a].addedNodes)for(let n=0;n<r[a].addedNodes.length;n++)r[a].addedNodes[n].classList&&r[a].addedNodes[n].classList.contains("thread-body")&&l()}};new MutationObserver(o).observe(e,t),console.log("DOM Mutation Observer init")}setTimeout(()=>{let e=document;g(),l(),A(e)},4e3)})();})();
